[project]
name = "memoryvault-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Anna Stefaniv Oickle",email = "anna.stefaniv.oickle@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "fastapi (>=0.136.0,<0.137.0)",
    "uvicorn (>=0.44.0,<0.45.0)",
    "sqlalchemy (>=2.0.49,<3.0.0)",
]

[tool.poetry]
packages = [{include = "memoryvault_backend", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
